Use special kernel headers for aarch64be-musl-stable
Just like we already do for aarch64-musl-stable, we need to use a
newer kernel headers version than 4.14: we use 4.19
instead. Otherwise, gdb fails to build with:

../../gdbserver/linux-aarch64-low.cc:760:61: error: ‘SVE_PT_REGS_SVE’ was not declared in this scope; did you mean ‘SVE_SIG_REGS_SIZE’?

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>